name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Upload static files as artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: |
            ./assets
            ./_dash-component-suites
            ./index.html
            ./_dash-layout.json
            ./_dash-dependencies.json