name: Build and Deploy to Github Pages
on:
  push:
    branches:
      - main
jobs:
  job_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          sudo apt-get install wget
          echo "Dependencies installed"

      - name: Build static page
        shell: bash
        run: |
            make clean
            make html
            echo "Static page built"
  job_upload:
    needs: job_build
    runs-on: ubuntu-latest
    steps:
      - name: Upload static files as artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: |
            ./assets
            ./_dash-component-suites
            ./index.html
            ./_dash-layout.json
            ./_dash-dependencies.json
